name: flutter_stacked_template
description: Flutter Stacked architecture template

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0

  ################### mine ###################
  # stacked
  stacked: ^1.7.6
  stacked_services: ^0.7.3
  stacked_hooks: ^0.1.4
  # widgets
  cached_network_image: ^2.2.0+1
  ################### mine end ###################

dev_dependencies:
  flutter_test:
    sdk: flutter

  ################### mine ###################
  build_runner:
  stacked_generator:
  ################### mine end ###################

flutter:
  uses-material-design: true
